"""描述你的更改

Revision ID: 5871a35cfd89
Revises: 8b621b35c9a7
Create Date: 2025-05-11 15:49:12.977407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5871a35cfd89'
down_revision = '8b621b35c9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_path', sa.String(length=512), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('is_file', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_share_token'))

    op.drop_table('share')
    # ### end Alembic commands ###
